const h="tab_lock_",u="locked_urls",a=(...t)=>console.log("[SecureShield]",...t);let i=new Set;chrome.storage.local.get(u,t=>{const e=t[u];e&&(i=new Set(e),a(`Loaded ${e.length} locked URLs from storage`))});self.addEventListener("install",()=>{a("Service worker installed")});self.addEventListener("activate",()=>{a("Service worker activated")});chrome.webNavigation.onBeforeNavigate.addListener(t=>{if(t.frameId!==0)return;const e=t.url;k(e)&&(a(`Blocking navigation to locked URL: ${e}`),chrome.tabs.update(t.tabId,{url:"about:blank"}),chrome.tabs.executeScript(t.tabId,{code:`
        document.body.innerHTML = \`
          <div style="display:flex;align-items:center;justify-content:center;min-height:100vh;font-family:system-ui;background:#f3f4f6;">
            <div style="text-align:center;max-width:500px;padding:2rem;">
              <div style="width:80px;height:80px;margin:0 auto 1.5rem;background:#ef4444;border-radius:50%;display:flex;align-items:center;justify-content:center;">
                <svg width="48" height="48" fill="white" viewBox="0 0 24 24">
                  <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 11c-.55 0-1-.45-1-1V8c0-.55.45-1 1-1s1 .45 1 1v4c0 .55-.45 1-1 1zm1 4h-2v-2h2v2z"/>
                </svg>
              </div>
              <h1 style="font-size:1.5rem;font-weight:600;color:#111;margin:0 0 0.5rem;">This tab is locked</h1>
              <p style="color:#6b7280;margin:0 0 1.5rem;">This URL is secured with a PIN. Unlock it from the SecureShield extension to access.</p>
              <p style="font-size:0.875rem;color:#9ca3af;word-break:break-all;">${e}</p>
            </div>
          </div>
        \`;
      `}))});chrome.runtime.onMessage.addListener((t,e,c)=>{const{action:o,payload:r}=t,s=l=>{l.then(n=>c({success:!0,data:n})).catch(n=>{a(`Action ${o} failed`,n.message),c({success:!1,error:n.message})})};switch(o){case"GET_CURRENT_TABS":s(m());break;case"GET_ACTIVE_TAB":s(g());break;case"GET_LOCKED_URLS":s(Promise.resolve(Array.from(i)));break;case"LOCK_TABS":if(!(r!=null&&r.lockId)||!r.tabs)return c({success:!1,error:"Missing lockId or tabs"}),!1;s(b(r.lockId,r.tabs));break;case"UNLOCK_TABS":if(!(r!=null&&r.lockId))return c({success:!1,error:"Missing lockId"}),!1;s(w(r.lockId));break;default:return c({success:!1,error:"Unknown action"}),!1}return!0});async function m(){return(await chrome.tabs.query({currentWindow:!0})).filter(e=>!!e.url&&!f(e.url)).map(e=>({title:e.title||new URL(e.url).hostname,url:e.url}))}async function g(){const e=(await chrome.tabs.query({active:!0,currentWindow:!0}))[0];if(!(e!=null&&e.url)||f(e.url))throw new Error("No active tab available for locking");return{title:e.title||new URL(e.url).hostname,url:e.url}}async function b(t,e){a(`Locking tabs for lock ${t}`);const c=await chrome.tabs.query({currentWindow:!0}),o=[];for(const l of e)i.add(l.url);await chrome.storage.local.set({[u]:Array.from(i)});for(const l of e){const n=c.find(d=>d.url===l.url&&typeof d.id=="number");n!=null&&n.id&&o.push(n.id)}const r=`${h}${t}`,s={lockId:t,tabs:e,tabIds:o,timestamp:Date.now()};await chrome.storage.local.set({[r]:s}),a(`Stored ${e.length} tab definitions (closing ${o.length})`),o.length&&(await chrome.tabs.remove(o),a(`Closed ${o.length} tabs`))}async function w(t){a(`Unlocking tabs for lock ${t}`);const e=`${h}${t}`,o=(await chrome.storage.local.get(e))[e];if(!o){a(`No stored state found for lock ${t}`);return}for(const r of o.tabs)i.delete(r.url);await chrome.storage.local.set({[u]:Array.from(i)});for(const r of o.tabs)try{await chrome.tabs.create({url:r.url,active:!1})}catch(s){a(`Failed to reopen tab ${r.url}`,s)}await chrome.storage.local.remove(e),a(`Cleared stored state for lock ${t}`)}function f(t){return t.startsWith("chrome://")||t.startsWith("chrome-extension://")||t.startsWith("about:")}function k(t){return f(t)?!1:i.has(t)}
